// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RateLimitingSample.Data;

#nullable disable

namespace RateLimitingSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RateLimitingSample.Data.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cotton",
                            IsDone = false,
                            Title = "asymmetric"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ADP",
                            IsDone = true,
                            Title = "Future"
                        },
                        new
                        {
                            Id = 3,
                            Description = "empowering",
                            IsDone = true,
                            Title = "solid state"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Director",
                            IsDone = false,
                            Title = "digital"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fantastic Metal Chicken",
                            IsDone = false,
                            Title = "Tasty Concrete Bike"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Granite",
                            IsDone = false,
                            Title = "incremental"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Intelligent Rubber Chair",
                            IsDone = true,
                            Title = "backing up"
                        },
                        new
                        {
                            Id = 8,
                            Description = "transmitter",
                            IsDone = true,
                            Title = "Expanded"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ergonomic Metal Computer",
                            IsDone = false,
                            Title = "mint green"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Village",
                            IsDone = true,
                            Title = "Concrete"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Industrial",
                            IsDone = true,
                            Title = "salmon"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Toys, Clothing & Books",
                            IsDone = false,
                            Title = "Checking Account"
                        },
                        new
                        {
                            Id = 13,
                            Description = "local area network",
                            IsDone = true,
                            Title = "Keys"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Circles",
                            IsDone = false,
                            Title = "quantifying"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Creek",
                            IsDone = true,
                            Title = "back-end"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Manors",
                            IsDone = false,
                            Title = "discrete"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Money Market Account",
                            IsDone = false,
                            Title = "yellow"
                        },
                        new
                        {
                            Id = 18,
                            Description = "deposit",
                            IsDone = true,
                            Title = "Checking Account"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Personal Loan Account",
                            IsDone = true,
                            Title = "Graphical User Interface"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Toys",
                            IsDone = false,
                            Title = "algorithm"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Accounts",
                            IsDone = false,
                            Title = "Lempira"
                        },
                        new
                        {
                            Id = 22,
                            Description = "engineer",
                            IsDone = false,
                            Title = "Grove"
                        },
                        new
                        {
                            Id = 23,
                            Description = "gold",
                            IsDone = false,
                            Title = "programming"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Consultant",
                            IsDone = false,
                            Title = "sensor"
                        },
                        new
                        {
                            Id = 25,
                            Description = "multimedia",
                            IsDone = true,
                            Title = "Personal Loan Account"
                        },
                        new
                        {
                            Id = 26,
                            Description = "TCP",
                            IsDone = true,
                            Title = "transmit"
                        },
                        new
                        {
                            Id = 27,
                            Description = "local area network",
                            IsDone = false,
                            Title = "Coordinator"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Union",
                            IsDone = true,
                            Title = "Ecuador"
                        },
                        new
                        {
                            Id = 29,
                            Description = "sky blue",
                            IsDone = false,
                            Title = "mindshare"
                        },
                        new
                        {
                            Id = 30,
                            Description = "fuchsia",
                            IsDone = true,
                            Title = "Missouri"
                        },
                        new
                        {
                            Id = 31,
                            Description = "application",
                            IsDone = true,
                            Title = "Pines"
                        },
                        new
                        {
                            Id = 32,
                            Description = "incubate",
                            IsDone = false,
                            Title = "Baby, Baby & Sports"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Intelligent Granite Fish",
                            IsDone = false,
                            Title = "Team-oriented"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Money Market Account",
                            IsDone = true,
                            Title = "Way"
                        },
                        new
                        {
                            Id = 35,
                            Description = "deposit",
                            IsDone = true,
                            Title = "dedicated"
                        },
                        new
                        {
                            Id = 36,
                            Description = "quantify",
                            IsDone = false,
                            Title = "overriding"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Sports & Health",
                            IsDone = false,
                            Title = "Buckinghamshire"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Implementation",
                            IsDone = false,
                            Title = "connecting"
                        },
                        new
                        {
                            Id = 39,
                            Description = "blue",
                            IsDone = false,
                            Title = "red"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Springs",
                            IsDone = true,
                            Title = "Organized"
                        },
                        new
                        {
                            Id = 41,
                            Description = "portals",
                            IsDone = false,
                            Title = "Shoes"
                        },
                        new
                        {
                            Id = 42,
                            Description = "gold",
                            IsDone = true,
                            Title = "hack"
                        },
                        new
                        {
                            Id = 43,
                            Description = "auxiliary",
                            IsDone = true,
                            Title = "Home Loan Account"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Stravenue",
                            IsDone = false,
                            Title = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Meadows",
                            IsDone = true,
                            Title = "RSS"
                        },
                        new
                        {
                            Id = 46,
                            Description = "deposit",
                            IsDone = false,
                            Title = "programming"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Infrastructure",
                            IsDone = true,
                            Title = "viral"
                        },
                        new
                        {
                            Id = 48,
                            Description = "gold",
                            IsDone = true,
                            Title = "synergies"
                        },
                        new
                        {
                            Id = 49,
                            Description = "invoice",
                            IsDone = true,
                            Title = "Senior"
                        },
                        new
                        {
                            Id = 50,
                            Description = "South Carolina",
                            IsDone = false,
                            Title = "protocol"
                        },
                        new
                        {
                            Id = 51,
                            Description = "driver",
                            IsDone = false,
                            Title = "infomediaries"
                        },
                        new
                        {
                            Id = 52,
                            Description = "generating",
                            IsDone = true,
                            Title = "Rustic Soft Chips"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Isle of Man",
                            IsDone = true,
                            Title = "Multi-layered"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Court",
                            IsDone = false,
                            Title = "Jewelery"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Producer",
                            IsDone = true,
                            Title = "convergence"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Metal",
                            IsDone = false,
                            Title = "Wooden"
                        },
                        new
                        {
                            Id = 57,
                            Description = "index",
                            IsDone = true,
                            Title = "utilisation"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Divide",
                            IsDone = false,
                            Title = "Auto Loan Account"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Granite",
                            IsDone = true,
                            Title = "Metal"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Port",
                            IsDone = true,
                            Title = "digital"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Auto Loan Account",
                            IsDone = true,
                            Title = "Generic Granite Pizza"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Oval",
                            IsDone = true,
                            Title = "Berkshire"
                        },
                        new
                        {
                            Id = 63,
                            Description = "array",
                            IsDone = true,
                            Title = "bandwidth"
                        },
                        new
                        {
                            Id = 64,
                            Description = "capacitor",
                            IsDone = false,
                            Title = "Buckinghamshire"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Intelligent Fresh Fish",
                            IsDone = true,
                            Title = "generating"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Place",
                            IsDone = false,
                            Title = "River"
                        },
                        new
                        {
                            Id = 67,
                            Description = "reintermediate",
                            IsDone = true,
                            Title = "invoice"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Gambia",
                            IsDone = false,
                            Title = "Cote d'Ivoire"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Streamlined",
                            IsDone = true,
                            Title = "target"
                        },
                        new
                        {
                            Id = 70,
                            Description = "withdrawal",
                            IsDone = false,
                            Title = "Savings Account"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Home, Books & Books",
                            IsDone = false,
                            Title = "cyan"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Vermont",
                            IsDone = true,
                            Title = "Incredible Steel Pizza"
                        },
                        new
                        {
                            Id = 73,
                            Description = "GB",
                            IsDone = false,
                            Title = "compelling"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Bulgaria",
                            IsDone = false,
                            Title = "Savings Account"
                        },
                        new
                        {
                            Id = 75,
                            Description = "copy",
                            IsDone = true,
                            Title = "Division"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Handcrafted",
                            IsDone = false,
                            Title = "programming"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Engineer",
                            IsDone = true,
                            Title = "indexing"
                        },
                        new
                        {
                            Id = 78,
                            Description = "reboot",
                            IsDone = false,
                            Title = "application"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Unbranded Soft Chips",
                            IsDone = false,
                            Title = "withdrawal"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Vermont",
                            IsDone = false,
                            Title = "THX"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Faroe Islands",
                            IsDone = false,
                            Title = "Avon"
                        },
                        new
                        {
                            Id = 82,
                            Description = "cross-media",
                            IsDone = true,
                            Title = "Incredible"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Credit Card Account",
                            IsDone = true,
                            Title = "quantifying"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Berkshire",
                            IsDone = true,
                            Title = "Unbranded Soft Hat"
                        },
                        new
                        {
                            Id = 85,
                            Description = "redefine",
                            IsDone = true,
                            Title = "Computers, Jewelery & Baby"
                        },
                        new
                        {
                            Id = 86,
                            Description = "orange",
                            IsDone = true,
                            Title = "Coordinator"
                        },
                        new
                        {
                            Id = 87,
                            Description = "protocol",
                            IsDone = true,
                            Title = "Intranet"
                        },
                        new
                        {
                            Id = 88,
                            Description = "auxiliary",
                            IsDone = false,
                            Title = "Fields"
                        },
                        new
                        {
                            Id = 89,
                            Description = "compress",
                            IsDone = false,
                            Title = "XML"
                        },
                        new
                        {
                            Id = 90,
                            Description = "relationships",
                            IsDone = true,
                            Title = "Liberian Dollar"
                        },
                        new
                        {
                            Id = 91,
                            Description = "compressing",
                            IsDone = false,
                            Title = "Rustic Cotton Bike"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Toys, Shoes & Home",
                            IsDone = true,
                            Title = "programming"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Unbranded",
                            IsDone = true,
                            Title = "New Hampshire"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Creek",
                            IsDone = false,
                            Title = "Lodge"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Solutions",
                            IsDone = true,
                            Title = "Cotton"
                        },
                        new
                        {
                            Id = 96,
                            Description = "withdrawal",
                            IsDone = true,
                            Title = "Handmade Granite Pants"
                        },
                        new
                        {
                            Id = 97,
                            Description = "hybrid",
                            IsDone = false,
                            Title = "array"
                        },
                        new
                        {
                            Id = 98,
                            Description = "virtual",
                            IsDone = true,
                            Title = "Personal Loan Account"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Handmade Wooden Fish",
                            IsDone = false,
                            Title = "Avon"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Buckinghamshire",
                            IsDone = false,
                            Title = "infomediaries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
